/**
 * @archivo src/presentation/dashboard/dashboard-styles.ts
 * @proposito Define los estilos visuales del Dashboard sin acoplarlos al Worker.
 * @responsabilidades Exponer el lenguaje visual del Dashboard como recurso de presentación independiente.
 * @ubicacion src/presentation/dashboard dentro de la arquitectura de QvaPay-AI.
 */

import { ACCESSIBILITY_POLICY } from "../accessibility/accessibility-policy.js";
import { MOTION_POLICY } from "../motion/motion-policy.js";
import { DESIGN_TOKENS } from "../tokens/design-tokens.js";

export const DASHBOARD_STYLES = `${DESIGN_TOKENS}${ACCESSIBILITY_POLICY}${MOTION_POLICY}${String.raw`<style>

:root{color-scheme:dark;--bg:var(--qva-color-background);--panel:var(--qva-color-surface);--panel2:var(--qva-color-surface-raised);--line:var(--qva-color-border);--text:var(--qva-color-text);--muted:var(--qva-color-text-muted);--good:var(--qva-color-positive);--warn:var(--qva-color-warning);--bad:var(--qva-color-negative);--accent:var(--qva-color-accent);--buy:var(--qva-color-buy);--sell:var(--qva-color-sell);--gold:#ffd746;font-family:var(--qva-font-ui)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0,#16233f,transparent 34%),radial-gradient(circle at 90% 8%,#211a3e,transparent 30%),var(--bg);color:var(--text)}a{color:inherit;text-decoration:none}button{font:inherit} :focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.skip-link{position:fixed;left:12px;top:12px;z-index:100;padding:10px 13px;border-radius:9px;background:#101a2d;color:var(--text);border:1px solid var(--line);transform:translateY(-180%);transition:transform .15s}.skip-link:focus{transform:translateY(0)}.shell{display:grid;grid-template-columns:245px 1fr;min-height:100vh}.sidebar{position:sticky;top:0;height:100vh;padding:20px 15px;border-right:1px solid var(--line);background:rgba(7,11,20,.9);backdrop-filter:blur(18px);z-index:10}.brand{display:flex;gap:11px;align-items:center;padding:4px 8px 22px}.logo{width:43px;height:43px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#6f8cff,#9b6dff);font-size:22px}.brand strong{display:block}.brand span{font-size:10px;color:var(--muted)}nav{display:grid;gap:6px}.navitem{display:flex;gap:10px;align-items:center;padding:11px 12px;border:1px solid transparent;border-radius:11px;color:var(--muted);font-size:13px;font-weight:750;transition:.2s}.navitem:hover,.navitem.active{color:var(--text);background:#101a2d;border-color:#263758;transform:translateX(2px)}.navicon{width:22px;text-align:center}.framework{position:absolute;left:15px;right:15px;bottom:18px;padding:12px;border:1px solid var(--line);border-radius:13px;background:#0b1220}.framework b{font-size:10px}.framework p{margin:7px 0 0;color:var(--muted);font-size:9px;line-height:1.5}
main{min-width:0;padding:22px clamp(15px,3vw,40px) 42px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.title h1{margin:0;font-size:clamp(24px,3vw,34px)}.title p{margin:5px 0 0;color:var(--muted);font-size:13px}.live{display:flex;align-items:center;gap:8px;padding:10px 13px;border:1px solid var(--line);border-radius:999px;background:#0b1220;font-size:11px}.dot{width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 14px var(--good);animation:pulse 1.8s infinite}.live.bad .dot{background:var(--bad);box-shadow:0 0 14px var(--bad)}
section{scroll-margin-top:24px}.hero{margin-top:22px;display:grid;grid-template-columns:1.45fr .9fr;gap:15px}.panel{background:linear-gradient(145deg,rgba(17,26,45,.95),rgba(10,16,29,.95));border:1px solid var(--line);border-radius:19px;box-shadow:0 18px 55px rgba(0,0,0,.25);transition:.25s}.panel:hover{border-color:#314368}.overview{padding:23px}.eyebrow{color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.coin{font-size:40px;font-weight:850;margin:6px 0}.health-row{display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap}.health{display:flex;gap:8px;align-items:center;color:var(--good);font-size:12px}.next{display:flex;align-items:center;gap:9px}.countdown{font-variant-numeric:tabular-nums;font-size:27px;font-weight:850;color:var(--accent)}.countdown small{font-size:9px;color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:17px}.metric{padding:14px;border-radius:13px;background:rgba(6,11,22,.65);border:1px solid #1e2a44}.metric span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.06em}.metric b{display:block;margin-top:5px;font-size:17px}.best{padding:21px}.bestgrid{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:13px}.quote{padding:17px;border-radius:15px;background:#0a1220}.quote.buy{border:1px solid rgba(71,215,160,.35);animation:heartbeat 1.8s infinite}.quote.sell{border:1px solid rgba(255,120,144,.35);animation:heartbeat 1.8s infinite}.side{font-size:10px;font-weight:850;letter-spacing:.08em}.buy .side{color:var(--buy)}.sell .side{color:var(--sell)}.rate{font-size:24px;font-weight:850;margin:7px 0}.small{font-size:10px;color:var(--muted);line-height:1.5}
.section{margin-top:18px}.section-title{display:flex;justify-content:space-between;align-items:end;gap:10px;margin:0 0 10px}.section-title h2{font-size:18px;margin:0}.section-title p{margin:3px 0 0;color:var(--muted);font-size:11px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.control{padding:16px;border-radius:15px}.control-head{display:flex;justify-content:space-between;gap:9px}.control h3{font-size:13px;margin:0}.control p{font-size:10px;color:var(--muted);line-height:1.5;margin:9px 0 0}.status{display:inline-flex;padding:5px 7px;border-radius:999px;font-size:9px;font-weight:800;background:rgba(85,227,154,.1);color:var(--good);white-space:nowrap}.status.warn{background:rgba(244,201,93,.1);color:var(--warn)}.status.bad{background:rgba(255,113,136,.1);color:var(--bad)}
.tables{display:grid;gap:15px}.tablepanel{overflow:hidden}.tablehead{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid var(--line)}.tablehead h2{font-size:15px;margin:0}.badge{font-size:9px;color:var(--muted);padding:5px 7px;border:1px solid var(--line);border-radius:999px}.table-scroll{overflow-x:auto;width:100%}.table-scroll table{min-width:960px;table-layout:fixed}table{width:100%;border-collapse:collapse}.market-col-created{width:16%}.market-col-user{width:15%}.market-col-amount{width:12%}.market-col-rate{width:13%}.market-col-fiat{width:12%}.market-col-vip{width:10%}.market-col-status{width:10%}.market-col-action{width:12%}th,td{text-align:right;padding:11px 14px;border-bottom:1px solid rgba(36,49,77,.55);font-variant-numeric:tabular-nums}th:first-child,td:first-child{text-align:left}th{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}td{font-size:13px}tbody tr:hover td{background:rgba(124,156,255,.07)}.statusbadge,.vipbadge,.reserved{display:inline-flex;align-items:center;justify-content:center;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:800;white-space:nowrap}.status-open,.status-completed{background:rgba(85,227,154,.12);color:var(--good)}.status-revision,.status-paid{background:rgba(244,201,93,.12);color:var(--warn)}.status-processing{background:rgba(124,156,255,.12);color:var(--accent)}.status-cancelled{background:rgba(255,113,136,.12);color:var(--bad)}.vipbadge{background:rgba(244,201,93,.12);color:var(--warn)}.reserved{background:rgba(85,227,154,.12);color:var(--good)}.action{border:0;border-radius:8px;padding:9px 12px;font-size:12px;font-weight:850;color:#fff;cursor:pointer;transition:.18s}.action:hover{transform:translateY(-2px);filter:brightness(1.08)}.action-buy{background:linear-gradient(135deg,#16a765,#42e69a)}.action-sell{background:linear-gradient(135deg,#d83d59,#ff7188)}.action:disabled{opacity:.55;cursor:wait}.ratecell{font-weight:800}.buyrate{color:var(--buy)}.sellrate{color:var(--sell)}tr.best-offer td{animation:best 1.8s infinite;background:rgba(255,215,70,.12);box-shadow:inset 0 0 18px rgba(255,215,70,.12),0 0 8px rgba(255,215,70,.10)}tr.best-offer td:first-child{border-left:3px solid var(--gold);box-shadow:inset 3px 0 18px rgba(255,215,70,.24)}tr.best-offer td:last-child{border-right:3px solid var(--gold);box-shadow:inset -3px 0 18px rgba(255,215,70,.24)}.empty{padding:32px;text-align:center;color:var(--muted)}
.audit{display:grid;grid-template-columns:1.2fr 1fr;gap:11px}.timeline,.trace{padding:17px}.event{display:grid;grid-template-columns:100px 1fr;gap:13px;padding:11px 0;border-bottom:1px solid rgba(36,49,77,.5)}.event:last-child{border-bottom:0}.event time{font-size:9px;color:var(--muted)}.event b{font-size:11px}.event p{margin:4px 0 0;font-size:10px;color:var(--muted)}.trace-row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid rgba(36,49,77,.5);font-size:10px}.trace-row:last-child{border-bottom:0}.trace-row span{color:var(--muted)}.footer{margin-top:17px;display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;color:var(--muted);font-size:9px}.tags{display:flex;gap:7px;flex-wrap:wrap}.tag{padding:5px 7px;border:1px solid #1d2942;border-radius:7px}
.field{display:grid;gap:6px;margin:10px 0}.field label{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}.field input{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:#080f1d;color:var(--text);outline:none}.field input:focus{border-color:var(--accent)}.button{border:0;border-radius:9px;padding:10px 13px;font-weight:800;cursor:pointer}.button.primary{background:linear-gradient(135deg,#6f8cff,#9b6dff);color:#fff}.button:disabled{opacity:.6;cursor:wait}.account-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:10px}.account-grid>div{padding:10px;border:1px solid rgba(36,49,77,.7);border-radius:8px;background:rgba(7,11,20,.28)}.account-grid span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.06em}.account-grid b{display:block;margin-top:4px;font-size:11px;overflow-wrap:anywhere}@media(max-width:760px){.account-grid{grid-template-columns:1fr}}
@keyframes pulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.5);opacity:.55}}@keyframes heartbeat{0%,100%{transform:scale(1)}14%{transform:scale(1.012)}28%{transform:scale(1)}42%{transform:scale(1.008)}}@keyframes best{0%,100%{background:rgba(255,215,70,.12);box-shadow:inset 0 0 18px rgba(255,215,70,.12),0 0 8px rgba(255,215,70,.10)}14%{background:rgba(255,215,70,.52);box-shadow:inset 0 0 34px rgba(255,215,70,.34),0 0 24px rgba(255,215,70,.28)}28%{background:rgba(255,215,70,.12);box-shadow:inset 0 0 18px rgba(255,215,70,.12),0 0 8px rgba(255,215,70,.10)}42%{background:rgba(255,215,70,.38);box-shadow:inset 0 0 28px rgba(255,215,70,.26),0 0 18px rgba(255,215,70,.20)}}@media(max-width:1050px){.shell{grid-template-columns:78px 1fr}.brand div:not(.logo),.navitem span:not(.navicon),.framework{display:none}.brand{justify-content:center}.navitem{justify-content:center}.hero,.audit{grid-template-columns:1fr}.grid3{grid-template-columns:1fr 1fr}}@media(max-width:760px){.shell{display:block}.sidebar{position:sticky;height:auto;padding:7px;display:flex;align-items:center;overflow:auto}.brand{padding:4px 7px}.sidebar nav{display:flex;min-width:max-content}.framework{display:none}main{padding:15px 10px 30px}.metrics,.grid3{grid-template-columns:1fr 1fr}.bestgrid{grid-template-columns:1fr}.event{grid-template-columns:72px 1fr}}@media(max-width:500px){.metrics,.grid3{grid-template-columns:1fr}.title h1{font-size:24px}}

</style>`}`;
